# Generated by Django 3.0.6 on 2020-05-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QandA',
            new_name='Question',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='text',
        ),
    ]
