# Generated by Django 3.0.6 on 2020-05-10 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_parent_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='show_on_web',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
