# Generated by Django 3.0.6 on 2020-06-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20200625_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='allow_user_submitted_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='real_time_results',
            field=models.BooleanField(default=False),
        ),
    ]
