# Generated by Django 3.0.6 on 2020-06-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20200625_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='allow_user_submitted_questions',
        ),
        migrations.AddField(
            model_name='survey',
            name='max_responses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='type',
            field=models.CharField(choices=[('YN', 'Yes/No'), ('FF', 'Freeform')], default='FF', max_length=3),
        ),
    ]
