# Generated by Django 3.0.6 on 2020-06-28 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0004_auto_20200628_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='template',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='surveyquestionresponse',
            unique_together={('survey_response', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='surveyresponse',
            unique_together={('user', 'survey')},
        ),
    ]
