# Generated by Django 3.0.6 on 2020-06-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20200628_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='ajax_template',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
