# Generated by Django 3.0.6 on 2020-06-29 00:13

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_survey_ajax_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='aa', editable=False, populate_from=models.CharField(max_length=256)),
            preserve_default=False,
        ),
    ]
