# Generated by Django 3.0.6 on 2020-06-29 12:39

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_survey_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
